version: "3.9"
services:
  node1:
    image: hyperledger/besu:24.7.1
    container_name: besu-node1
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./nodes/node1/.data:/besu/data
      - ./nodes/node1/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.11
    command: >
      --config-file=/besu/config/besu.config.toml

  node2:
    image: hyperledger/besu:24.7.1
    container_name: besu-node2
    ports:
      - 8555:8545
      - 8556:8546
    volumes:
      - ./nodes/node2/.data:/besu/data
      - ./nodes/node2/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.12
    command: >
      --config-file=/besu/config/besu.config.toml

  node3:
    image: hyperledger/besu:24.7.1
    container_name: besu-node3
    ports:
      - 8565:8545
      - 8566:8546
    volumes:
      - ./nodes/node3/.data:/besu/data
      - ./nodes/node3/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.13
    command: >
      --config-file=/besu/config/besu.config.toml

  node4:
    image: hyperledger/besu:24.7.1
    container_name: besu-node4
    ports:
      - 8575:8545
      - 8576:8546
    volumes:
      - ./nodes/node4/.data:/besu/data
      - ./nodes/node4/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.14
    command: >
      --config-file=/besu/config/besu.config.toml

  node5:
    image: hyperledger/besu:24.7.1
    container_name: besu-node5
    ports:
      - 8585:8545
      - 8586:8546
    volumes:
      - ./nodes/node5/.data:/besu/data
      - ./nodes/node5/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.15
    command: >
      --config-file=/besu/config/besu.config.toml

networks:
  besu-chain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
