version: "3.9"
services:
  node1:
    image: hyperledger/besu:24.7.1
    container_name: besu-node1
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303   # For node discovering
    volumes:
      - ./node1/.data:/besu/data
      - ./node1/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.11
    command: >
      --config-file=/besu/config/besu.config.toml

  node2:
    image: hyperledger/besu:24.7.1
    container_name: besu-node2
    ports:
      - 8555:8545
      - 8556:8546
      - 30304:30303   # For node discovering
    volumes:
      - ./node2/.data:/besu/data
      - ./node2/.env:/besu/secret
      - ./common/config:/besu/config
    networks:
      besu-chain:
        ipv4_address: 172.28.0.12
    command: >
      --config-file=/besu/config/besu.config.toml

  node3:
    build: .
    image: hyperledger/besu-curl:24.7.1
    container_name: besu-node3
    depends_on:
      - node1
    ports:
      - 8565:8545
      - 8566:8546
      - 30305:30303   # For node discovering
    volumes:
      - ./node3/.data:/besu/data
      - ./node3/.env:/besu/secret
      - ./common/config:/besu/config
      - ./run_besu_with_bootnodes.sh:/besu/scripts/run_besu_with_bootnodes.sh
    networks:
      besu-chain:
        ipv4_address: 172.28.0.13
    entrypoint: ["/besu/scripts/run_besu_with_bootnodes.sh"]
    command: >
      --config-file=/besu/config/besu.config.toml
      bootnodes=172.28.0.11:8545

  node4:
    build: .
    image: hyperledger/besu-curl:24.7.1
    container_name: besu-node4
    depends_on:
      - node2
    ports:
      - 8575:8545
      - 8576:8546
      - 30306:30303   # For node discovering
    volumes:
      - ./node4/.data:/besu/data
      - ./node4/.env:/besu/secret
      - ./common/config:/besu/config
      - ./run_besu_with_bootnodes.sh:/besu/scripts/run_besu_with_bootnodes.sh
    networks:
      besu-chain:
        ipv4_address: 172.28.0.14
    entrypoint: ["/besu/scripts/run_besu_with_bootnodes.sh"]
    command: >
      --config-file=/besu/config/besu.config.toml
      bootnodes=172.28.0.12:8545

  node5:
    build: .
    image: hyperledger/besu-curl:24.7.1
    container_name: besu-node5
    depends_on:
      - node1
      - node2
    ports:
      - 8585:8545
      - 8586:8546
      - 30307:30303   # For node discovering
    volumes:
      - ./node5/.data:/besu/data
      - ./node5/.env:/besu/secret
      - ./common/config:/besu/config
      - ./run_besu_with_bootnodes.sh:/besu/scripts/run_besu_with_bootnodes.sh
    networks:
      besu-chain:
        ipv4_address: 172.28.0.15
    entrypoint: ["/besu/scripts/run_besu_with_bootnodes.sh"]
    command: >
      --config-file=/besu/config/besu.config.toml
      bootnodes=172.28.0.11:8545,172.28.0.12:8545

  node6:
    build: .
    image: hyperledger/besu-curl:24.7.1
    container_name: besu-node6
    depends_on:
      - node1
      - node4
      - node5
    ports:
      - 8595:8545
      - 8596:8546
      - 30308:30303   # For node discovering
    volumes:
      - ./node6/.data:/besu/data
      - ./node6/.env:/besu/secret
      - ./common/config:/besu/config
      - ./run_besu_with_bootnodes.sh:/besu/scripts/run_besu_with_bootnodes.sh
    networks:
      besu-chain:
        ipv4_address: 172.28.0.16
    entrypoint: ["/besu/scripts/run_besu_with_bootnodes.sh"]
    command: >
      --config-file=/besu/config/besu.config.toml
      bootnodes=172.28.0.11:8545,172.28.0.14:8545,172.28.0.15:8545

  node7:
    build: .
    image: hyperledger/besu-curl:24.7.1
    container_name: besu-node7
    depends_on:
      - node6
    ports:
      - 8505:8545
      - 8506:8546
      - 30309:30303   # For node discovering
    volumes:
      - ./node7/.data:/besu/data
      - ./node7/.env:/besu/secret
      - ./common/config:/besu/config
      - ./run_besu_with_bootnodes.sh:/besu/scripts/run_besu_with_bootnodes.sh
    networks:
      besu-chain:
        ipv4_address: 172.28.0.17
    entrypoint: ["/besu/scripts/run_besu_with_bootnodes.sh"]
    command: >
      --config-file=/besu/config/besu.config.toml
      bootnodes=172.28.0.16:8545
      delay=12

networks:
  besu-chain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
